/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apg_Q__ */

#ifndef _Included_apg_Q__
#define _Included_apg_Q__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     apg_Q__
 * Method:    findOrthogonalVector
 * Signature: (IDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_apg_Q_00024_findOrthogonalVector
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble);

/*
 * Class:     apg_Q__
 * Method:    expQTtx
 * Signature: (IIIDDDD[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_apg_Q_00024_expQTtx
  (JNIEnv *, jobject, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
