/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apg_QMath__ */

#ifndef _Included_apg_QMath__
#define _Included_apg_QMath__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     apg_QMath__
 * Method:    findOrthogonalVector
 * Signature: (IDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_apg_QMath_00024_findOrthogonalVector
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble);

/*
 * Class:     apg_QMath__
 * Method:    expQTtx
 * Signature: (IDDDD[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_apg_QMath_00024_expQTtx
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
